
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-v1beta1-app
  failurePolicy: Fail
  name: vapp.shipcaps.redradrat.xyz
  rules:
  - apiGroups:
    - shipcaps.redradrat.xyz
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apps
