# permissions for end users to view caps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cap-viewer-role
rules:
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - caps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - caps/status
  verbs:
  - get
