# permissions for end users to edit caps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cap-editor-role
rules:
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - caps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - caps/status
  verbs:
  - get
