# permissions for end users to edit capdeps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capdep-editor-role
rules:
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capdeps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capdeps/status
  verbs:
  - get
