# permissions for end users to view capdeps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capdep-viewer-role
rules:
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capdeps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capdeps/status
  verbs:
  - get
