# permissions for end users to view capmaterials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capmaterial-viewer-role
rules:
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capmaterials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capmaterials/status
  verbs:
  - get
