# permissions for end users to edit capmaterials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capmaterial-editor-role
rules:
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capmaterials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - capmaterials/status
  verbs:
  - get
