# permissions for end users to edit clustercaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustercap-editor-role
rules:
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - clustercaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - clustercaps/status
  verbs:
  - get
