# permissions for end users to view clustercaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustercap-viewer-role
rules:
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - clustercaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shipcaps.redradrat.xyz
  resources:
  - clustercaps/status
  verbs:
  - get
