apiVersion: shipcaps.redradrat.xyz/v1beta1
kind: Cap
metadata:
  name: postgres
spec:
  type: helmchart
  inputs:
  - key: dbname
    type: string
  - key: dbadmin
    type: string
  - key: dbadminpassword
    type: password
    optional: true
  - key: dbusers
    type: stringlist
    optional: true
  material:
    repo:
      uri: https://github.com/redradrat/charts
      ref: v1.0
    path: /postgres
    manifests:
      apiVersion: v1
      kind: List
      items:
      - apiVersion: v1
        kind: Namespace
        metadata: bla
      - apiVersion: v1
        kind: Namespace
        metadata: blabla


