apiVersion: shipcaps.redradrat.xyz/v1beta1
kind: Cap
metadata:
  name: postgres
spec:
  type: helmchart
  inputs:
  - key: dbname
    type: string
    targetId: db.name
  - key: dbadmin
    type: string
    targetId: db.admin.name
  - key: dbadminpassword
    type: password
    optional: true
    targetId: db.admin.password
  - key: dbusers
    type: stringlist
    optional: true
    targetId: db.users
  values:
    - value: "teststring"
      targetId: db.somestring
  material:
    repo:
      uri: https://github.com/redradrat/charts
      ref: v1.0
    path: /postgres
