apiVersion: shipcaps.redradrat.xyz/v1beta1
kind: Cap
metadata:
  name: test
spec:
  type: helmchart
  inputs:
    - key: ingressClass
      type: string
      targetId: helloworld.service.ingressClass
  values:
    - value: anotherone
      targetId: helloworld.service.testValue
  material:
    type: repo
    repo:
      uri: https://github.com/stakater-charts/helloworld
      path: helloworld
      ref: master
    manifests:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: test
