apiVersion: shipcaps.redradrat.xyz/v1beta1
kind: Cap
metadata:
  name: test
spec:
  inputs:
    - key: ingressClass
      type: string
      targetId: helloworld.service.ingressClass
  values:
    - value: anotherone
      targetId: helloworld.service.testValue
  source:
    type: helmchart
    repo:
      uri: https://github.com/stakater-charts/helloworld
      path: helloworld
      ref: master